# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  solhint:
    name: runner / solhint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: solhint
        uses: contractshark/inject-solhint-ci@latest
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review # Change reporter.
          solhint_input: 'contracts/*.sol'

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 16.8.0 ]
    steps:
      - name: Count Lines of Code (cloc)
        uses: djdefi/cloc-action@3

      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm init -y
      - run: npm install truffle@5.6.7 -g
      - run: npm install ganache-cli -g
      - run: npm install cloc -g
      - run: npm install
      - run: nohup ganache-cli --gasLimit 8000000 &
      - run: truffle test

  coverage:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 16.8.0 ]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - run: npm install
      - run: npx hardhat coverage

      - uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true
          files: ./coverage/lcov.info
          flags: production