# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 14.17.5 ]

    steps:
      - name: Count Lines of Code (cloc)
        uses: djdefi/cloc-action@3

      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm init -y
      - run: npm install truffle@5.6.7 -g
      - run: npm install ganache-cli -g
      - run: npm install cloc -g
      - run: npm install
      - run: nohup ganache-cli --gasLimit 8000000 &
      - run: truffle test
      - run: npx hardhat coverage

      - uses: actions/checkout@master
      - uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos